// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/internal/database/model"
)

func newAnswer(db *gorm.DB, opts ...gen.DOOption) answer {
	_answer := answer{}

	_answer.answerDo.UseDB(db, opts...)
	_answer.answerDo.UseModel(&model.Answer{})

	tableName := _answer.answerDo.TableName()
	_answer.ALL = field.NewAsterisk(tableName)
	_answer.CreatedAt = field.NewTime(tableName, "created_at")
	_answer.UpdatedAt = field.NewTime(tableName, "updated_at")
	_answer.DeletedAt = field.NewField(tableName, "deleted_at")
	_answer.Id = field.NewString(tableName, "id")
	_answer.QuestionId = field.NewString(tableName, "question_id")
	_answer.Content = field.NewString(tableName, "content")
	_answer.IsPublic = field.NewBool(tableName, "is_public")
	_answer.AttachedImageList = answerHasManyAttachedImageList{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("AttachedImageList", "model.ImageFile"),
	}

	_answer.fillFieldMap()

	return _answer
}

type answer struct {
	answerDo

	ALL               field.Asterisk
	CreatedAt         field.Time
	UpdatedAt         field.Time
	DeletedAt         field.Field
	Id                field.String
	QuestionId        field.String
	Content           field.String
	IsPublic          field.Bool
	AttachedImageList answerHasManyAttachedImageList

	fieldMap map[string]field.Expr
}

func (a answer) Table(newTableName string) *answer {
	a.answerDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a answer) As(alias string) *answer {
	a.answerDo.DO = *(a.answerDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *answer) updateTableName(table string) *answer {
	a.ALL = field.NewAsterisk(table)
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.Id = field.NewString(table, "id")
	a.QuestionId = field.NewString(table, "question_id")
	a.Content = field.NewString(table, "content")
	a.IsPublic = field.NewBool(table, "is_public")

	a.fillFieldMap()

	return a
}

func (a *answer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *answer) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 8)
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["id"] = a.Id
	a.fieldMap["question_id"] = a.QuestionId
	a.fieldMap["content"] = a.Content
	a.fieldMap["is_public"] = a.IsPublic

}

func (a answer) clone(db *gorm.DB) answer {
	a.answerDo.ReplaceConnPool(db.Statement.ConnPool)
	a.AttachedImageList.db = db.Session(&gorm.Session{Initialized: true})
	a.AttachedImageList.db.Statement.ConnPool = db.Statement.ConnPool
	return a
}

func (a answer) replaceDB(db *gorm.DB) answer {
	a.answerDo.ReplaceDB(db)
	a.AttachedImageList.db = db.Session(&gorm.Session{})
	return a
}

type answerHasManyAttachedImageList struct {
	db *gorm.DB

	field.RelationField
}

func (a answerHasManyAttachedImageList) Where(conds ...field.Expr) *answerHasManyAttachedImageList {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a answerHasManyAttachedImageList) WithContext(ctx context.Context) *answerHasManyAttachedImageList {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a answerHasManyAttachedImageList) Session(session *gorm.Session) *answerHasManyAttachedImageList {
	a.db = a.db.Session(session)
	return &a
}

func (a answerHasManyAttachedImageList) Model(m *model.Answer) *answerHasManyAttachedImageListTx {
	return &answerHasManyAttachedImageListTx{a.db.Model(m).Association(a.Name())}
}

func (a answerHasManyAttachedImageList) Unscoped() *answerHasManyAttachedImageList {
	a.db = a.db.Unscoped()
	return &a
}

type answerHasManyAttachedImageListTx struct{ tx *gorm.Association }

func (a answerHasManyAttachedImageListTx) Find() (result []*model.ImageFile, err error) {
	return result, a.tx.Find(&result)
}

func (a answerHasManyAttachedImageListTx) Append(values ...*model.ImageFile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a answerHasManyAttachedImageListTx) Replace(values ...*model.ImageFile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a answerHasManyAttachedImageListTx) Delete(values ...*model.ImageFile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a answerHasManyAttachedImageListTx) Clear() error {
	return a.tx.Clear()
}

func (a answerHasManyAttachedImageListTx) Count() int64 {
	return a.tx.Count()
}

func (a answerHasManyAttachedImageListTx) Unscoped() *answerHasManyAttachedImageListTx {
	a.tx = a.tx.Unscoped()
	return &a
}

type answerDo struct{ gen.DO }

type IAnswerDo interface {
	gen.SubQuery
	Debug() IAnswerDo
	WithContext(ctx context.Context) IAnswerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IAnswerDo
	WriteDB() IAnswerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IAnswerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IAnswerDo
	Not(conds ...gen.Condition) IAnswerDo
	Or(conds ...gen.Condition) IAnswerDo
	Select(conds ...field.Expr) IAnswerDo
	Where(conds ...gen.Condition) IAnswerDo
	Order(conds ...field.Expr) IAnswerDo
	Distinct(cols ...field.Expr) IAnswerDo
	Omit(cols ...field.Expr) IAnswerDo
	Join(table schema.Tabler, on ...field.Expr) IAnswerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IAnswerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IAnswerDo
	Group(cols ...field.Expr) IAnswerDo
	Having(conds ...gen.Condition) IAnswerDo
	Limit(limit int) IAnswerDo
	Offset(offset int) IAnswerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IAnswerDo
	Unscoped() IAnswerDo
	Create(values ...*model.Answer) error
	CreateInBatches(values []*model.Answer, batchSize int) error
	Save(values ...*model.Answer) error
	First() (*model.Answer, error)
	Take() (*model.Answer, error)
	Last() (*model.Answer, error)
	Find() ([]*model.Answer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Answer, err error)
	FindInBatches(result *[]*model.Answer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Answer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IAnswerDo
	Assign(attrs ...field.AssignExpr) IAnswerDo
	Joins(fields ...field.RelationField) IAnswerDo
	Preload(fields ...field.RelationField) IAnswerDo
	FirstOrInit() (*model.Answer, error)
	FirstOrCreate() (*model.Answer, error)
	FindByPage(offset int, limit int) (result []*model.Answer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IAnswerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a answerDo) Debug() IAnswerDo {
	return a.withDO(a.DO.Debug())
}

func (a answerDo) WithContext(ctx context.Context) IAnswerDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a answerDo) ReadDB() IAnswerDo {
	return a.Clauses(dbresolver.Read)
}

func (a answerDo) WriteDB() IAnswerDo {
	return a.Clauses(dbresolver.Write)
}

func (a answerDo) Session(config *gorm.Session) IAnswerDo {
	return a.withDO(a.DO.Session(config))
}

func (a answerDo) Clauses(conds ...clause.Expression) IAnswerDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a answerDo) Returning(value interface{}, columns ...string) IAnswerDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a answerDo) Not(conds ...gen.Condition) IAnswerDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a answerDo) Or(conds ...gen.Condition) IAnswerDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a answerDo) Select(conds ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a answerDo) Where(conds ...gen.Condition) IAnswerDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a answerDo) Order(conds ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a answerDo) Distinct(cols ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a answerDo) Omit(cols ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a answerDo) Join(table schema.Tabler, on ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a answerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a answerDo) RightJoin(table schema.Tabler, on ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a answerDo) Group(cols ...field.Expr) IAnswerDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a answerDo) Having(conds ...gen.Condition) IAnswerDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a answerDo) Limit(limit int) IAnswerDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a answerDo) Offset(offset int) IAnswerDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a answerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IAnswerDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a answerDo) Unscoped() IAnswerDo {
	return a.withDO(a.DO.Unscoped())
}

func (a answerDo) Create(values ...*model.Answer) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a answerDo) CreateInBatches(values []*model.Answer, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a answerDo) Save(values ...*model.Answer) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a answerDo) First() (*model.Answer, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Answer), nil
	}
}

func (a answerDo) Take() (*model.Answer, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Answer), nil
	}
}

func (a answerDo) Last() (*model.Answer, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Answer), nil
	}
}

func (a answerDo) Find() ([]*model.Answer, error) {
	result, err := a.DO.Find()
	return result.([]*model.Answer), err
}

func (a answerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Answer, err error) {
	buf := make([]*model.Answer, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a answerDo) FindInBatches(result *[]*model.Answer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a answerDo) Attrs(attrs ...field.AssignExpr) IAnswerDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a answerDo) Assign(attrs ...field.AssignExpr) IAnswerDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a answerDo) Joins(fields ...field.RelationField) IAnswerDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a answerDo) Preload(fields ...field.RelationField) IAnswerDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a answerDo) FirstOrInit() (*model.Answer, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Answer), nil
	}
}

func (a answerDo) FirstOrCreate() (*model.Answer, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Answer), nil
	}
}

func (a answerDo) FindByPage(offset int, limit int) (result []*model.Answer, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a answerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a answerDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a answerDo) Delete(models ...*model.Answer) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *answerDo) withDO(do gen.Dao) *answerDo {
	a.DO = *do.(*gen.DO)
	return a
}
