// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"backend/internal/database"
)

func newImageFile(db *gorm.DB, opts ...gen.DOOption) imageFile {
	_imageFile := imageFile{}

	_imageFile.imageFileDo.UseDB(db, opts...)
	_imageFile.imageFileDo.UseModel(&database.ImageFile{})

	tableName := _imageFile.imageFileDo.TableName()
	_imageFile.ALL = field.NewAsterisk(tableName)
	_imageFile.CreatedAt = field.NewTime(tableName, "created_at")
	_imageFile.UpdatedAt = field.NewTime(tableName, "updated_at")
	_imageFile.DeletedAt = field.NewField(tableName, "deleted_at")
	_imageFile.Id = field.NewString(tableName, "id")
	_imageFile.OriginalName = field.NewString(tableName, "original_name")
	_imageFile.MimeType = field.NewString(tableName, "mime_type")
	_imageFile.Size = field.NewInt64(tableName, "size")
	_imageFile.Url = field.NewString(tableName, "url")
	_imageFile.QuestionId = field.NewString(tableName, "question_id")

	_imageFile.fillFieldMap()

	return _imageFile
}

type imageFile struct {
	imageFileDo

	ALL          field.Asterisk
	CreatedAt    field.Time
	UpdatedAt    field.Time
	DeletedAt    field.Field
	Id           field.String
	OriginalName field.String
	MimeType     field.String
	Size         field.Int64
	Url          field.String
	QuestionId   field.String

	fieldMap map[string]field.Expr
}

func (i imageFile) Table(newTableName string) *imageFile {
	i.imageFileDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i imageFile) As(alias string) *imageFile {
	i.imageFileDo.DO = *(i.imageFileDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *imageFile) updateTableName(table string) *imageFile {
	i.ALL = field.NewAsterisk(table)
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")
	i.Id = field.NewString(table, "id")
	i.OriginalName = field.NewString(table, "original_name")
	i.MimeType = field.NewString(table, "mime_type")
	i.Size = field.NewInt64(table, "size")
	i.Url = field.NewString(table, "url")
	i.QuestionId = field.NewString(table, "question_id")

	i.fillFieldMap()

	return i
}

func (i *imageFile) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *imageFile) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
	i.fieldMap["id"] = i.Id
	i.fieldMap["original_name"] = i.OriginalName
	i.fieldMap["mime_type"] = i.MimeType
	i.fieldMap["size"] = i.Size
	i.fieldMap["url"] = i.Url
	i.fieldMap["question_id"] = i.QuestionId
}

func (i imageFile) clone(db *gorm.DB) imageFile {
	i.imageFileDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i imageFile) replaceDB(db *gorm.DB) imageFile {
	i.imageFileDo.ReplaceDB(db)
	return i
}

type imageFileDo struct{ gen.DO }

type IImageFileDo interface {
	gen.SubQuery
	Debug() IImageFileDo
	WithContext(ctx context.Context) IImageFileDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IImageFileDo
	WriteDB() IImageFileDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IImageFileDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IImageFileDo
	Not(conds ...gen.Condition) IImageFileDo
	Or(conds ...gen.Condition) IImageFileDo
	Select(conds ...field.Expr) IImageFileDo
	Where(conds ...gen.Condition) IImageFileDo
	Order(conds ...field.Expr) IImageFileDo
	Distinct(cols ...field.Expr) IImageFileDo
	Omit(cols ...field.Expr) IImageFileDo
	Join(table schema.Tabler, on ...field.Expr) IImageFileDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IImageFileDo
	RightJoin(table schema.Tabler, on ...field.Expr) IImageFileDo
	Group(cols ...field.Expr) IImageFileDo
	Having(conds ...gen.Condition) IImageFileDo
	Limit(limit int) IImageFileDo
	Offset(offset int) IImageFileDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IImageFileDo
	Unscoped() IImageFileDo
	Create(values ...*database.ImageFile) error
	CreateInBatches(values []*database.ImageFile, batchSize int) error
	Save(values ...*database.ImageFile) error
	First() (*database.ImageFile, error)
	Take() (*database.ImageFile, error)
	Last() (*database.ImageFile, error)
	Find() ([]*database.ImageFile, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.ImageFile, err error)
	FindInBatches(result *[]*database.ImageFile, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*database.ImageFile) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IImageFileDo
	Assign(attrs ...field.AssignExpr) IImageFileDo
	Joins(fields ...field.RelationField) IImageFileDo
	Preload(fields ...field.RelationField) IImageFileDo
	FirstOrInit() (*database.ImageFile, error)
	FirstOrCreate() (*database.ImageFile, error)
	FindByPage(offset int, limit int) (result []*database.ImageFile, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IImageFileDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i imageFileDo) Debug() IImageFileDo {
	return i.withDO(i.DO.Debug())
}

func (i imageFileDo) WithContext(ctx context.Context) IImageFileDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i imageFileDo) ReadDB() IImageFileDo {
	return i.Clauses(dbresolver.Read)
}

func (i imageFileDo) WriteDB() IImageFileDo {
	return i.Clauses(dbresolver.Write)
}

func (i imageFileDo) Session(config *gorm.Session) IImageFileDo {
	return i.withDO(i.DO.Session(config))
}

func (i imageFileDo) Clauses(conds ...clause.Expression) IImageFileDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i imageFileDo) Returning(value interface{}, columns ...string) IImageFileDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i imageFileDo) Not(conds ...gen.Condition) IImageFileDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i imageFileDo) Or(conds ...gen.Condition) IImageFileDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i imageFileDo) Select(conds ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i imageFileDo) Where(conds ...gen.Condition) IImageFileDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i imageFileDo) Order(conds ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i imageFileDo) Distinct(cols ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i imageFileDo) Omit(cols ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i imageFileDo) Join(table schema.Tabler, on ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i imageFileDo) LeftJoin(table schema.Tabler, on ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i imageFileDo) RightJoin(table schema.Tabler, on ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i imageFileDo) Group(cols ...field.Expr) IImageFileDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i imageFileDo) Having(conds ...gen.Condition) IImageFileDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i imageFileDo) Limit(limit int) IImageFileDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i imageFileDo) Offset(offset int) IImageFileDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i imageFileDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IImageFileDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i imageFileDo) Unscoped() IImageFileDo {
	return i.withDO(i.DO.Unscoped())
}

func (i imageFileDo) Create(values ...*database.ImageFile) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i imageFileDo) CreateInBatches(values []*database.ImageFile, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i imageFileDo) Save(values ...*database.ImageFile) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i imageFileDo) First() (*database.ImageFile, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*database.ImageFile), nil
	}
}

func (i imageFileDo) Take() (*database.ImageFile, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*database.ImageFile), nil
	}
}

func (i imageFileDo) Last() (*database.ImageFile, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*database.ImageFile), nil
	}
}

func (i imageFileDo) Find() ([]*database.ImageFile, error) {
	result, err := i.DO.Find()
	return result.([]*database.ImageFile), err
}

func (i imageFileDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*database.ImageFile, err error) {
	buf := make([]*database.ImageFile, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i imageFileDo) FindInBatches(result *[]*database.ImageFile, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i imageFileDo) Attrs(attrs ...field.AssignExpr) IImageFileDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i imageFileDo) Assign(attrs ...field.AssignExpr) IImageFileDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i imageFileDo) Joins(fields ...field.RelationField) IImageFileDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i imageFileDo) Preload(fields ...field.RelationField) IImageFileDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i imageFileDo) FirstOrInit() (*database.ImageFile, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*database.ImageFile), nil
	}
}

func (i imageFileDo) FirstOrCreate() (*database.ImageFile, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*database.ImageFile), nil
	}
}

func (i imageFileDo) FindByPage(offset int, limit int) (result []*database.ImageFile, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i imageFileDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i imageFileDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i imageFileDo) Delete(models ...*database.ImageFile) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *imageFileDo) withDO(do gen.Dao) *imageFileDo {
	i.DO = *do.(*gen.DO)
	return i
}
