// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	"testing"

	"backend/internal/database"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&database.ImageFile{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&database.ImageFile{}) fail: %s", err)
	}
}

func Test_imageFileQuery(t *testing.T) {
	imageFile := newImageFile(_gen_test_db)
	imageFile = *imageFile.As(imageFile.TableName())
	_do := imageFile.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(imageFile.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <image_files> fail:", err)
		return
	}

	_, ok := imageFile.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from imageFile success")
	}

	err = _do.Create(&database.ImageFile{})
	if err != nil {
		t.Error("create item in table <image_files> fail:", err)
	}

	err = _do.Save(&database.ImageFile{})
	if err != nil {
		t.Error("create item in table <image_files> fail:", err)
	}

	err = _do.CreateInBatches([]*database.ImageFile{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <image_files> fail:", err)
	}

	_, err = _do.Select(imageFile.ALL).Take()
	if err != nil {
		t.Error("Take() on table <image_files> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <image_files> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <image_files> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <image_files> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*database.ImageFile{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <image_files> fail:", err)
	}

	_, err = _do.Select(imageFile.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <image_files> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <image_files> fail:", err)
	}

	_, err = _do.Select(imageFile.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <image_files> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <image_files> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <image_files> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <image_files> fail:", err)
	}

	_, err = _do.ScanByPage(&database.ImageFile{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <image_files> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <image_files> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <image_files> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <image_files> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <image_files> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <image_files> fail:", err)
	}
}
