// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1-0.20250820092511-bdc4edce7476 DO NOT EDIT.
package schema

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ProfileType.
const (
	Email ProfileType = "email"
	Text  ProfileType = "text"
	Url   ProfileType = "url"
)

// Defines values for QuestionStatus.
const (
	Answered QuestionStatus = "answered"
	Read     QuestionStatus = "read"
	Unread   QuestionStatus = "unread"
)

// Defines values for ReportRequestTargetType.
const (
	ReportRequestTargetTypeQuestion ReportRequestTargetType = "question"
	ReportRequestTargetTypeUser     ReportRequestTargetType = "user"
)

// Defines values for SortOrder.
const (
	Asc  SortOrder = "asc"
	Desc SortOrder = "desc"
)

// Defines values for QuestionFilterSortBy.
const (
	QuestionFilterSortByCreatedAt QuestionFilterSortBy = "createdAt"
	QuestionFilterSortByUpdatedAt QuestionFilterSortBy = "updatedAt"
)

// Defines values for SentQuestionFilterSortBy.
const (
	SentQuestionFilterSortByCreatedAt SentQuestionFilterSortBy = "createdAt"
	SentQuestionFilterSortByUpdatedAt SentQuestionFilterSortBy = "updatedAt"
)

// Defines values for GetPublicQAsParamsSortBy.
const (
	GetPublicQAsParamsSortByCreatedAt GetPublicQAsParamsSortBy = "createdAt"
	GetPublicQAsParamsSortByUpdatedAt GetPublicQAsParamsSortBy = "updatedAt"
)

// Defines values for GetReceivedQuestionsParamsSortBy.
const (
	GetReceivedQuestionsParamsSortByCreatedAt GetReceivedQuestionsParamsSortBy = "createdAt"
	GetReceivedQuestionsParamsSortByUpdatedAt GetReceivedQuestionsParamsSortBy = "updatedAt"
)

// Defines values for GetSentQuestionsParamsSortBy.
const (
	CreatedAt GetSentQuestionsParamsSortBy = "createdAt"
	UpdatedAt GetSentQuestionsParamsSortBy = "updatedAt"
)

// Answer 回答
type Answer struct {
	AttachedImageList *[]ImageFile `json:"attachedImageList,omitempty"`
	Content           string       `json:"content"`
	CreatedAt         time.Time    `json:"createdAt"`
	Id                string       `json:"id"`
	IsPublic          bool         `json:"isPublic"`
	QuestionId        string       `json:"questionId"`
	UpdatedAt         time.Time    `json:"updatedAt"`
}

// AnswerCreateRequest 回答作成リクエスト
type AnswerCreateRequest struct {
	AttachedImageIdList *[]string `json:"attachedImageIdList,omitempty"`
	Content             string    `json:"content"`
	IsPublic            bool      `json:"isPublic"`
}

// BlockedUser ブロックユーザー情報
type BlockedUser struct {
	// BlockedUser 公開用ユーザー情報
	BlockedUser PublicUserInfo `json:"blockedUser"`
	CreatedAt   time.Time      `json:"createdAt"`
	Id          string         `json:"id"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

// ErrorDetails エラー詳細情報
type ErrorDetails struct {
	Code    *string     `json:"code,omitempty"`
	Details interface{} `json:"details,omitempty"`
	Message string      `json:"message"`
}

// Identificator defines model for Identificator.
type Identificator struct {
	union json.RawMessage
}

// Identificator0 defines model for .
type Identificator0 = string

// Identificator1 defines model for .
type Identificator1 = string

// ImageFile 画像ファイル情報
type ImageFile struct {
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	MimeType     string    `json:"mimeType"`
	OriginalName string    `json:"originalName"`
	Size         int64     `json:"size"`
	Url          string    `json:"url"`
}

// LoginRequest ログインリクエスト
type LoginRequest struct {
	Id       Identificator `json:"id"`
	Password string        `json:"password"`
}

// LoginResponse ログインレスポンス
type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`

	// User ユーザープロフィール情報
	User User `json:"user"`
}

// NgWord NGワード
type NgWord struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	IsActive  bool      `json:"isActive"`
	UpdatedAt time.Time `json:"updatedAt"`
	Word      string    `json:"word"`
}

// NgWordCreateRequest NGワード追加リクエスト
type NgWordCreateRequest struct {
	Word string `json:"word"`
}

// ProfileBase プロフィール項目ベース
type ProfileBase struct {
	CreatedAt time.Time   `json:"createdAt"`
	Id        string      `json:"id"`
	Name      string      `json:"name"`
	Order     int32       `json:"order"`
	Type      ProfileType `json:"type"`
	UpdatedAt time.Time   `json:"updatedAt"`
	Value     string      `json:"value"`
}

// ProfileEmail プロフィール項目ベース
type ProfileEmail = ProfileBase

// ProfileField プロフィール項目
type ProfileField struct {
	union json.RawMessage
}

// ProfileFieldUpdate プロフィール更新
type ProfileFieldUpdate struct {
	Id        *string `json:"id,omitempty"`
	IsVisible bool    `json:"isVisible"`
	Name      string  `json:"name"`
	Order     int32   `json:"order"`
	Value     string  `json:"value"`
}

// ProfileSite プロフィール項目ベース
type ProfileSite = ProfileBase

// ProfileTwitter プロフィール項目ベース
type ProfileTwitter = ProfileBase

// ProfileType defines model for ProfileType.
type ProfileType string

// ProfileUpdateRequest ユーザー情報更新リクエスト
type ProfileUpdateRequest struct {
	DisplayId     *string               `json:"displayId,omitempty"`
	DisplayName   *string               `json:"displayName,omitempty"`
	Email         *string               `json:"email,omitempty"`
	IconImageId   *string               `json:"iconImageId,omitempty"`
	ProfileFields *[]ProfileFieldUpdate `json:"profileFields,omitempty"`
}

// PublicQA 公開された質問・回答セット
type PublicQA struct {
	Answer struct {
		AttachedImageList *[]ImageFile `json:"attachedImageList,omitempty"`
		Content           string       `json:"content"`
		CreatedAt         time.Time    `json:"createdAt"`
	} `json:"answer"`

	// AnsweredBy 公開用ユーザー情報
	AnsweredBy PublicUserInfo `json:"answeredBy"`
	Id         string         `json:"id"`
	Question   struct {
		AttachedImageList *[]ImageFile `json:"attachedImageList,omitempty"`
		Content           string       `json:"content"`
		CreatedAt         time.Time    `json:"createdAt"`
		IsAnonymous       bool         `json:"isAnonymous"`
	} `json:"question"`
}

// PublicUserInfo 公開用ユーザー情報
type PublicUserInfo struct {
	DisplayId   string `json:"displayId"`
	DisplayName string `json:"displayName"`

	// IconImage 画像ファイル情報
	IconImage     *ImageFile      `json:"iconImage,omitempty"`
	ProfileFields *[]ProfileField `json:"profileFields,omitempty"`
}

// Question defines model for Question.
type Question = QuestionBase

// QuestionBase defines model for QuestionBase.
type QuestionBase struct {
	AttachedImageList *[]ImageFile `json:"attachedImageList,omitempty"`

	// Content 質問本文
	Content     string    `json:"content"`
	CreatedAt   time.Time `json:"createdAt"`
	Id          string    `json:"id"`
	IsAnonymous bool      `json:"isAnonymous"`

	// RecipientId 受信者ID
	RecipientId string `json:"recipientId"`

	// SenderId 送信者ID ログインユーザーの場合のみ
	SenderId *string `json:"senderId,omitempty"`

	// Status 質問ステータス
	Status    QuestionStatus `json:"status"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

// QuestionCreateRequest 質問送信リクエスト
type QuestionCreateRequest struct {
	AttachedImageIdList *[]string `json:"attachedImageIdList,omitempty"`
	Content             string    `json:"content"`
	RecipientId         string    `json:"recipientId"`
}

// QuestionDetail 質問
type QuestionDetail = Question

// QuestionStatus 質問ステータス
type QuestionStatus string

// QuestionUpdateRequest 質問編集リクエスト
type QuestionUpdateRequest struct {
	AttachedImageIdList *[]string `json:"attachedImageIdList,omitempty"`
	Content             *string   `json:"content,omitempty"`
}

// ReportRequest 通報リクエスト
type ReportRequest struct {
	Details    *string                 `json:"details,omitempty"`
	Reason     string                  `json:"reason"`
	TargetId   string                  `json:"targetId"`
	TargetType ReportRequestTargetType `json:"targetType"`
}

// ReportRequestTargetType defines model for ReportRequest.TargetType.
type ReportRequestTargetType string

// SortOrder ソート順序
type SortOrder string

// User ユーザープロフィール情報
type User struct {
	CreatedAt time.Time `json:"createdAt"`

	// DisplayId ユーザーID（表示用、一意）
	DisplayId   string `json:"displayId"`
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`

	// IconImage 画像ファイル情報
	IconImage *ImageFile `json:"iconImage,omitempty"`

	// Id 内部ID
	Id            string          `json:"id"`
	IsActive      bool            `json:"isActive"`
	ProfileFields *[]ProfileField `json:"profileFields,omitempty"`
	UpdatedAt     time.Time       `json:"updatedAt"`
}

// UserRegistrationRequest ユーザー登録リクエスト
type UserRegistrationRequest struct {
	DisplayId   string `json:"displayId"`
	DisplayName string `json:"displayName"`
	Email       string `json:"email"`
	Password    string `json:"password"`
}

// PaginationQueryLimit defines model for PaginationQuery.limit.
type PaginationQueryLimit = int32

// PaginationQueryPage defines model for PaginationQuery.page.
type PaginationQueryPage = int32

// QuestionFilterSortBy defines model for QuestionFilter.sortBy.
type QuestionFilterSortBy string

// QuestionFilterSortOrder ソート順序
type QuestionFilterSortOrder = SortOrder

// QuestionFilterStatus 質問ステータス
type QuestionFilterStatus = QuestionStatus

// SentQuestionFilterHasAnswer defines model for SentQuestionFilter.hasAnswer.
type SentQuestionFilterHasAnswer = bool

// SentQuestionFilterSortBy defines model for SentQuestionFilter.sortBy.
type SentQuestionFilterSortBy string

// SentQuestionFilterSortOrder ソート順序
type SentQuestionFilterSortOrder = SortOrder

// GetPublicQAsParams defines parameters for GetPublicQAs.
type GetPublicQAsParams struct {
	Page      *PaginationQueryPage      `form:"page,omitempty" json:"page,omitempty"`
	Limit     *PaginationQueryLimit     `form:"limit,omitempty" json:"limit,omitempty"`
	SortBy    *GetPublicQAsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortOrder *SortOrder                `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// GetPublicQAsParamsSortBy defines parameters for GetPublicQAs.
type GetPublicQAsParamsSortBy string

// GetReceivedQuestionsParams defines parameters for GetReceivedQuestions.
type GetReceivedQuestionsParams struct {
	Page      *PaginationQueryPage              `form:"page,omitempty" json:"page,omitempty"`
	Limit     *PaginationQueryLimit             `form:"limit,omitempty" json:"limit,omitempty"`
	Status    *QuestionFilterStatus             `form:"status,omitempty" json:"status,omitempty"`
	SortBy    *GetReceivedQuestionsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortOrder *QuestionFilterSortOrder          `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// GetReceivedQuestionsParamsSortBy defines parameters for GetReceivedQuestions.
type GetReceivedQuestionsParamsSortBy string

// GetSentQuestionsParams defines parameters for GetSentQuestions.
type GetSentQuestionsParams struct {
	Page      *PaginationQueryPage          `form:"page,omitempty" json:"page,omitempty"`
	Limit     *PaginationQueryLimit         `form:"limit,omitempty" json:"limit,omitempty"`
	HasAnswer *SentQuestionFilterHasAnswer  `form:"hasAnswer,omitempty" json:"hasAnswer,omitempty"`
	SortBy    *GetSentQuestionsParamsSortBy `form:"sortBy,omitempty" json:"sortBy,omitempty"`
	SortOrder *SentQuestionFilterSortOrder  `form:"sortOrder,omitempty" json:"sortOrder,omitempty"`
}

// GetSentQuestionsParamsSortBy defines parameters for GetSentQuestions.
type GetSentQuestionsParamsSortBy string

// BlockUserJSONBody defines parameters for BlockUser.
type BlockUserJSONBody struct {
	UserId string `json:"userId"`
}

// GetBlockedUsersParams defines parameters for GetBlockedUsers.
type GetBlockedUsersParams struct {
	Page  *PaginationQueryPage  `form:"page,omitempty" json:"page,omitempty"`
	Limit *PaginationQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetNgWordsParams defines parameters for GetNgWords.
type GetNgWordsParams struct {
	Page  *PaginationQueryPage  `form:"page,omitempty" json:"page,omitempty"`
	Limit *PaginationQueryLimit `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateQuestionJSONRequestBody defines body for CreateQuestion for application/json ContentType.
type CreateQuestionJSONRequestBody = QuestionCreateRequest

// ReportContentJSONRequestBody defines body for ReportContent for application/json ContentType.
type ReportContentJSONRequestBody = ReportRequest

// UpdateQuestionJSONRequestBody defines body for UpdateQuestion for application/json ContentType.
type UpdateQuestionJSONRequestBody = QuestionUpdateRequest

// CreateAnswerJSONRequestBody defines body for CreateAnswer for application/json ContentType.
type CreateAnswerJSONRequestBody = AnswerCreateRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = UserRegistrationRequest

// BlockUserJSONRequestBody defines body for BlockUser for application/json ContentType.
type BlockUserJSONRequestBody BlockUserJSONBody

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// UpdateUserProfileJSONRequestBody defines body for UpdateUserProfile for application/json ContentType.
type UpdateUserProfileJSONRequestBody = ProfileUpdateRequest

// AddNgWordJSONRequestBody defines body for AddNgWord for application/json ContentType.
type AddNgWordJSONRequestBody = NgWordCreateRequest

// AsIdentificator0 returns the union data inside the Identificator as a Identificator0
func (t Identificator) AsIdentificator0() (Identificator0, error) {
	var body Identificator0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIdentificator0 overwrites any union data inside the Identificator as the provided Identificator0
func (t *Identificator) FromIdentificator0(v Identificator0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIdentificator0 performs a merge with any union data inside the Identificator, using the provided Identificator0
func (t *Identificator) MergeIdentificator0(v Identificator0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIdentificator1 returns the union data inside the Identificator as a Identificator1
func (t Identificator) AsIdentificator1() (Identificator1, error) {
	var body Identificator1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIdentificator1 overwrites any union data inside the Identificator as the provided Identificator1
func (t *Identificator) FromIdentificator1(v Identificator1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIdentificator1 performs a merge with any union data inside the Identificator, using the provided Identificator1
func (t *Identificator) MergeIdentificator1(v Identificator1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Identificator) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Identificator) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsProfileTwitter returns the union data inside the ProfileField as a ProfileTwitter
func (t ProfileField) AsProfileTwitter() (ProfileTwitter, error) {
	var body ProfileTwitter
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProfileTwitter overwrites any union data inside the ProfileField as the provided ProfileTwitter
func (t *ProfileField) FromProfileTwitter(v ProfileTwitter) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProfileTwitter performs a merge with any union data inside the ProfileField, using the provided ProfileTwitter
func (t *ProfileField) MergeProfileTwitter(v ProfileTwitter) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProfileSite returns the union data inside the ProfileField as a ProfileSite
func (t ProfileField) AsProfileSite() (ProfileSite, error) {
	var body ProfileSite
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProfileSite overwrites any union data inside the ProfileField as the provided ProfileSite
func (t *ProfileField) FromProfileSite(v ProfileSite) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProfileSite performs a merge with any union data inside the ProfileField, using the provided ProfileSite
func (t *ProfileField) MergeProfileSite(v ProfileSite) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProfileEmail returns the union data inside the ProfileField as a ProfileEmail
func (t ProfileField) AsProfileEmail() (ProfileEmail, error) {
	var body ProfileEmail
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProfileEmail overwrites any union data inside the ProfileField as the provided ProfileEmail
func (t *ProfileField) FromProfileEmail(v ProfileEmail) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProfileEmail performs a merge with any union data inside the ProfileField, using the provided ProfileEmail
func (t *ProfileField) MergeProfileEmail(v ProfileEmail) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ProfileField) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ProfileField) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 画像ファイルをアップロード
	// (POST /api/files/images)
	UploadImage(ctx echo.Context) error
	// 画像ファイルを削除
	// (DELETE /api/files/images/{imageId})
	DeleteImage(ctx echo.Context, imageId string) error
	// 画像ファイルを取得
	// (GET /api/files/images/{imageId})
	GetImage(ctx echo.Context, imageId string) error
	// 新しい質問を送信
	// (POST /api/questions)
	CreateQuestion(ctx echo.Context) error
	// ユーザーの公開質問・回答一覧取得
	// (GET /api/questions/public/{userId})
	GetPublicQAs(ctx echo.Context, userId string, params GetPublicQAsParams) error
	// 受信した質問一覧取得
	// (GET /api/questions/received)
	GetReceivedQuestions(ctx echo.Context, params GetReceivedQuestionsParams) error
	// 不適切なコンテンツを通報
	// (POST /api/questions/report)
	ReportContent(ctx echo.Context) error
	// 送信した質問一覧取得
	// (GET /api/questions/sent)
	GetSentQuestions(ctx echo.Context, params GetSentQuestionsParams) error
	// 質問を削除
	// (DELETE /api/questions/{questionId})
	DeleteQuestion(ctx echo.Context, questionId string) error
	// 質問詳細情報取得
	// (GET /api/questions/{questionId})
	GetQuestionDetail(ctx echo.Context, questionId string) error
	// 質問内容を編集
	// (PATCH /api/questions/{questionId})
	UpdateQuestion(ctx echo.Context, questionId string) error
	// 質問に回答を作成
	// (POST /api/questions/{questionId}/answer)
	CreateAnswer(ctx echo.Context, questionId string) error
	// 質問を既読にマーク
	// (PATCH /api/questions/{questionId}/read)
	MarkQuestionAsRead(ctx echo.Context, questionId string) error
	// 新規ユーザー登録
	// (POST /api/users)
	RegisterUser(ctx echo.Context) error
	// ユーザーをブロック
	// (POST /api/users/block)
	BlockUser(ctx echo.Context) error
	// ユーザーのブロックを解除
	// (DELETE /api/users/block/{userId})
	UnblockUser(ctx echo.Context, userId string) error
	// ブロックしたユーザー一覧取得
	// (GET /api/users/blocked)
	GetBlockedUsers(ctx echo.Context, params GetBlockedUsersParams) error
	// ユーザーログイン
	// (POST /api/users/login)
	LoginUser(ctx echo.Context) error
	// ユーザーログアウト
	// (POST /api/users/logout)
	LogoutUser(ctx echo.Context) error
	// ログイン中のユーザー情報取得
	// (GET /api/users/me)
	GetCurrentUser(ctx echo.Context) error
	// ユーザープロフィール更新
	// (PATCH /api/users/me)
	UpdateUserProfile(ctx echo.Context) error
	// NGワード一覧取得
	// (GET /api/users/ng-words)
	GetNgWords(ctx echo.Context, params GetNgWordsParams) error
	// NGワードを追加
	// (POST /api/users/ng-words)
	AddNgWord(ctx echo.Context) error
	// NGワードを削除
	// (DELETE /api/users/ng-words/{ngWordId})
	DeleteNgWord(ctx echo.Context, ngWordId string) error
	// 公開ユーザー情報取得
	// (GET /api/users/{userId})
	GetPublicUserInfo(ctx echo.Context, userId string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// UploadImage converts echo context to params.
func (w *ServerInterfaceWrapper) UploadImage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UploadImage(ctx)
	return err
}

// DeleteImage converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "imageId" -------------
	var imageId string

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", ctx.Param("imageId"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter imageId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteImage(ctx, imageId)
	return err
}

// GetImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetImage(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "imageId" -------------
	var imageId string

	err = runtime.BindStyledParameterWithOptions("simple", "imageId", ctx.Param("imageId"), &imageId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter imageId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImage(ctx, imageId)
	return err
}

// CreateQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) CreateQuestion(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateQuestion(ctx)
	return err
}

// GetPublicQAs converts echo context to params.
func (w *ServerInterfaceWrapper) GetPublicQAs(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPublicQAsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", false, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", false, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", false, false, "sortBy", ctx.QueryParams(), &params.SortBy)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortBy: %s", err))
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", false, false, "sortOrder", ctx.QueryParams(), &params.SortOrder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortOrder: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPublicQAs(ctx, userId, params)
	return err
}

// GetReceivedQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) GetReceivedQuestions(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReceivedQuestionsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", false, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", false, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", false, false, "status", ctx.QueryParams(), &params.Status)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter status: %s", err))
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", false, false, "sortBy", ctx.QueryParams(), &params.SortBy)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortBy: %s", err))
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", false, false, "sortOrder", ctx.QueryParams(), &params.SortOrder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortOrder: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReceivedQuestions(ctx, params)
	return err
}

// ReportContent converts echo context to params.
func (w *ServerInterfaceWrapper) ReportContent(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReportContent(ctx)
	return err
}

// GetSentQuestions converts echo context to params.
func (w *ServerInterfaceWrapper) GetSentQuestions(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSentQuestionsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", false, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", false, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "hasAnswer" -------------

	err = runtime.BindQueryParameter("form", false, false, "hasAnswer", ctx.QueryParams(), &params.HasAnswer)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter hasAnswer: %s", err))
	}

	// ------------- Optional query parameter "sortBy" -------------

	err = runtime.BindQueryParameter("form", false, false, "sortBy", ctx.QueryParams(), &params.SortBy)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortBy: %s", err))
	}

	// ------------- Optional query parameter "sortOrder" -------------

	err = runtime.BindQueryParameter("form", false, false, "sortOrder", ctx.QueryParams(), &params.SortOrder)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter sortOrder: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSentQuestions(ctx, params)
	return err
}

// DeleteQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId string

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteQuestion(ctx, questionId)
	return err
}

// GetQuestionDetail converts echo context to params.
func (w *ServerInterfaceWrapper) GetQuestionDetail(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId string

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetQuestionDetail(ctx, questionId)
	return err
}

// UpdateQuestion converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateQuestion(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId string

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateQuestion(ctx, questionId)
	return err
}

// CreateAnswer converts echo context to params.
func (w *ServerInterfaceWrapper) CreateAnswer(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId string

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateAnswer(ctx, questionId)
	return err
}

// MarkQuestionAsRead converts echo context to params.
func (w *ServerInterfaceWrapper) MarkQuestionAsRead(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "questionId" -------------
	var questionId string

	err = runtime.BindStyledParameterWithOptions("simple", "questionId", ctx.Param("questionId"), &questionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter questionId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.MarkQuestionAsRead(ctx, questionId)
	return err
}

// RegisterUser converts echo context to params.
func (w *ServerInterfaceWrapper) RegisterUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RegisterUser(ctx)
	return err
}

// BlockUser converts echo context to params.
func (w *ServerInterfaceWrapper) BlockUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.BlockUser(ctx)
	return err
}

// UnblockUser converts echo context to params.
func (w *ServerInterfaceWrapper) UnblockUser(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UnblockUser(ctx, userId)
	return err
}

// GetBlockedUsers converts echo context to params.
func (w *ServerInterfaceWrapper) GetBlockedUsers(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBlockedUsersParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", false, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", false, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBlockedUsers(ctx, params)
	return err
}

// LoginUser converts echo context to params.
func (w *ServerInterfaceWrapper) LoginUser(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LoginUser(ctx)
	return err
}

// LogoutUser converts echo context to params.
func (w *ServerInterfaceWrapper) LogoutUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.LogoutUser(ctx)
	return err
}

// GetCurrentUser converts echo context to params.
func (w *ServerInterfaceWrapper) GetCurrentUser(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetCurrentUser(ctx)
	return err
}

// UpdateUserProfile converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateUserProfile(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateUserProfile(ctx)
	return err
}

// GetNgWords converts echo context to params.
func (w *ServerInterfaceWrapper) GetNgWords(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNgWordsParams
	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", false, false, "page", ctx.QueryParams(), &params.Page)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter page: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", false, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetNgWords(ctx, params)
	return err
}

// AddNgWord converts echo context to params.
func (w *ServerInterfaceWrapper) AddNgWord(ctx echo.Context) error {
	var err error

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.AddNgWord(ctx)
	return err
}

// DeleteNgWord converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteNgWord(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "ngWordId" -------------
	var ngWordId string

	err = runtime.BindStyledParameterWithOptions("simple", "ngWordId", ctx.Param("ngWordId"), &ngWordId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter ngWordId: %s", err))
	}

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteNgWord(ctx, ngWordId)
	return err
}

// GetPublicUserInfo converts echo context to params.
func (w *ServerInterfaceWrapper) GetPublicUserInfo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", ctx.Param("userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter userId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetPublicUserInfo(ctx, userId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/files/images", wrapper.UploadImage)
	router.DELETE(baseURL+"/api/files/images/:imageId", wrapper.DeleteImage)
	router.GET(baseURL+"/api/files/images/:imageId", wrapper.GetImage)
	router.POST(baseURL+"/api/questions", wrapper.CreateQuestion)
	router.GET(baseURL+"/api/questions/public/:userId", wrapper.GetPublicQAs)
	router.GET(baseURL+"/api/questions/received", wrapper.GetReceivedQuestions)
	router.POST(baseURL+"/api/questions/report", wrapper.ReportContent)
	router.GET(baseURL+"/api/questions/sent", wrapper.GetSentQuestions)
	router.DELETE(baseURL+"/api/questions/:questionId", wrapper.DeleteQuestion)
	router.GET(baseURL+"/api/questions/:questionId", wrapper.GetQuestionDetail)
	router.PATCH(baseURL+"/api/questions/:questionId", wrapper.UpdateQuestion)
	router.POST(baseURL+"/api/questions/:questionId/answer", wrapper.CreateAnswer)
	router.PATCH(baseURL+"/api/questions/:questionId/read", wrapper.MarkQuestionAsRead)
	router.POST(baseURL+"/api/users", wrapper.RegisterUser)
	router.POST(baseURL+"/api/users/block", wrapper.BlockUser)
	router.DELETE(baseURL+"/api/users/block/:userId", wrapper.UnblockUser)
	router.GET(baseURL+"/api/users/blocked", wrapper.GetBlockedUsers)
	router.POST(baseURL+"/api/users/login", wrapper.LoginUser)
	router.POST(baseURL+"/api/users/logout", wrapper.LogoutUser)
	router.GET(baseURL+"/api/users/me", wrapper.GetCurrentUser)
	router.PATCH(baseURL+"/api/users/me", wrapper.UpdateUserProfile)
	router.GET(baseURL+"/api/users/ng-words", wrapper.GetNgWords)
	router.POST(baseURL+"/api/users/ng-words", wrapper.AddNgWord)
	router.DELETE(baseURL+"/api/users/ng-words/:ngWordId", wrapper.DeleteNgWord)
	router.GET(baseURL+"/api/users/:userId", wrapper.GetPublicUserInfo)

}

type UploadImageRequestObject struct {
	Body io.Reader
}

type UploadImageResponseObject interface {
	VisitUploadImageResponse(w http.ResponseWriter) error
}

type UploadImage201JSONResponse struct {
	// Data 画像ファイル情報
	Data    *ImageFile `json:"data,omitempty"`
	Message *string    `json:"message,omitempty"`
}

func (response UploadImage201JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type UploadImage400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UploadImage400JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UploadImage413JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UploadImage413JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)

	return json.NewEncoder(w).Encode(response)
}

type UploadImage415JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UploadImage415JSONResponse) VisitUploadImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImageRequestObject struct {
	ImageId string `json:"imageId"`
}

type DeleteImageResponseObject interface {
	VisitDeleteImageResponse(w http.ResponseWriter) error
}

type DeleteImage200JSONResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

func (response DeleteImage200JSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImage401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteImage401JSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImage403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteImage403JSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteImage404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteImage404JSONResponse) VisitDeleteImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetImageRequestObject struct {
	ImageId string `json:"imageId"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200AsteriskResponse struct {
	Body          io.Reader
	ContentType   string
	ContentLength int64
}

func (response GetImage200AsteriskResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetImage404JSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateQuestionRequestObject struct {
	Body *CreateQuestionJSONRequestBody
}

type CreateQuestionResponseObject interface {
	VisitCreateQuestionResponse(w http.ResponseWriter) error
}

type CreateQuestion201JSONResponse struct {
	Data    *QuestionBase `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateQuestion201JSONResponse) VisitCreateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateQuestion400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateQuestion400JSONResponse) VisitCreateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateQuestion403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateQuestion403JSONResponse) VisitCreateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetPublicQAsRequestObject struct {
	UserId string `json:"userId"`
	Params GetPublicQAsParams
}

type GetPublicQAsResponseObject interface {
	VisitGetPublicQAsResponse(w http.ResponseWriter) error
}

type GetPublicQAs200JSONResponse struct {
	Data       []PublicQA `json:"data"`
	Pagination struct {
		Limit      int32 `json:"limit"`
		Page       int32 `json:"page"`
		Total      int32 `json:"total"`
		TotalPages int32 `json:"totalPages"`
	} `json:"pagination"`
}

func (response GetPublicQAs200JSONResponse) VisitGetPublicQAsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPublicQAs404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetPublicQAs404JSONResponse) VisitGetPublicQAsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetReceivedQuestionsRequestObject struct {
	Params GetReceivedQuestionsParams
}

type GetReceivedQuestionsResponseObject interface {
	VisitGetReceivedQuestionsResponse(w http.ResponseWriter) error
}

type GetReceivedQuestions200JSONResponse struct {
	Data       []Question `json:"data"`
	Pagination struct {
		Limit      int32 `json:"limit"`
		Page       int32 `json:"page"`
		Total      int32 `json:"total"`
		TotalPages int32 `json:"totalPages"`
	} `json:"pagination"`
}

func (response GetReceivedQuestions200JSONResponse) VisitGetReceivedQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetReceivedQuestions401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetReceivedQuestions401JSONResponse) VisitGetReceivedQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ReportContentRequestObject struct {
	Body *ReportContentJSONRequestBody
}

type ReportContentResponseObject interface {
	VisitReportContentResponse(w http.ResponseWriter) error
}

type ReportContent201JSONResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

func (response ReportContent201JSONResponse) VisitReportContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type ReportContent400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response ReportContent400JSONResponse) VisitReportContentResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetSentQuestionsRequestObject struct {
	Params GetSentQuestionsParams
}

type GetSentQuestionsResponseObject interface {
	VisitGetSentQuestionsResponse(w http.ResponseWriter) error
}

type GetSentQuestions200JSONResponse struct {
	Data       []Question `json:"data"`
	Pagination struct {
		Limit      int32 `json:"limit"`
		Page       int32 `json:"page"`
		Total      int32 `json:"total"`
		TotalPages int32 `json:"totalPages"`
	} `json:"pagination"`
}

func (response GetSentQuestions200JSONResponse) VisitGetSentQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetSentQuestions401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetSentQuestions401JSONResponse) VisitGetSentQuestionsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteQuestionRequestObject struct {
	QuestionId string `json:"questionId"`
}

type DeleteQuestionResponseObject interface {
	VisitDeleteQuestionResponse(w http.ResponseWriter) error
}

type DeleteQuestion200JSONResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

func (response DeleteQuestion200JSONResponse) VisitDeleteQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteQuestion401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteQuestion401JSONResponse) VisitDeleteQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteQuestion403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteQuestion403JSONResponse) VisitDeleteQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteQuestion404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteQuestion404JSONResponse) VisitDeleteQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionDetailRequestObject struct {
	QuestionId string `json:"questionId"`
}

type GetQuestionDetailResponseObject interface {
	VisitGetQuestionDetailResponse(w http.ResponseWriter) error
}

type GetQuestionDetail200JSONResponse struct {
	// Data 質問詳細（受信者視点）
	Data    *QuestionDetail `json:"data,omitempty"`
	Message *string         `json:"message,omitempty"`
}

func (response GetQuestionDetail200JSONResponse) VisitGetQuestionDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionDetail401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetQuestionDetail401JSONResponse) VisitGetQuestionDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionDetail403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetQuestionDetail403JSONResponse) VisitGetQuestionDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetQuestionDetail404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetQuestionDetail404JSONResponse) VisitGetQuestionDetailResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestionRequestObject struct {
	QuestionId string `json:"questionId"`
	Body       *UpdateQuestionJSONRequestBody
}

type UpdateQuestionResponseObject interface {
	VisitUpdateQuestionResponse(w http.ResponseWriter) error
}

type UpdateQuestion200JSONResponse struct {
	// Data 質問
	Data    *Question `json:"data,omitempty"`
	Message *string   `json:"message,omitempty"`
}

func (response UpdateQuestion200JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestion400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateQuestion400JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestion401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateQuestion401JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestion403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateQuestion403JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateQuestion404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateQuestion404JSONResponse) VisitUpdateQuestionResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateAnswerRequestObject struct {
	QuestionId string `json:"questionId"`
	Body       *CreateAnswerJSONRequestBody
}

type CreateAnswerResponseObject interface {
	VisitCreateAnswerResponse(w http.ResponseWriter) error
}

type CreateAnswer201JSONResponse struct {
	// Data 回答
	Data    *Answer `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response CreateAnswer201JSONResponse) VisitCreateAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateAnswer400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateAnswer400JSONResponse) VisitCreateAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateAnswer401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateAnswer401JSONResponse) VisitCreateAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateAnswer403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateAnswer403JSONResponse) VisitCreateAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateAnswer404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response CreateAnswer404JSONResponse) VisitCreateAnswerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type MarkQuestionAsReadRequestObject struct {
	QuestionId string `json:"questionId"`
}

type MarkQuestionAsReadResponseObject interface {
	VisitMarkQuestionAsReadResponse(w http.ResponseWriter) error
}

type MarkQuestionAsRead200JSONResponse struct {
	// Data 質問
	Data    *Question `json:"data,omitempty"`
	Message *string   `json:"message,omitempty"`
}

func (response MarkQuestionAsRead200JSONResponse) VisitMarkQuestionAsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type MarkQuestionAsRead401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response MarkQuestionAsRead401JSONResponse) VisitMarkQuestionAsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type MarkQuestionAsRead403JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response MarkQuestionAsRead403JSONResponse) VisitMarkQuestionAsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type MarkQuestionAsRead404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response MarkQuestionAsRead404JSONResponse) VisitMarkQuestionAsReadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUserRequestObject struct {
	Body *RegisterUserJSONRequestBody
}

type RegisterUserResponseObject interface {
	VisitRegisterUserResponse(w http.ResponseWriter) error
}

type RegisterUser201JSONResponse struct {
	// Data ユーザープロフィール情報
	Data    *User   `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response RegisterUser201JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response RegisterUser400JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type RegisterUser409JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response RegisterUser409JSONResponse) VisitRegisterUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type BlockUserRequestObject struct {
	Body *BlockUserJSONRequestBody
}

type BlockUserResponseObject interface {
	VisitBlockUserResponse(w http.ResponseWriter) error
}

type BlockUser201JSONResponse struct {
	// Data ブロックユーザー情報
	Data    *BlockedUser `json:"data,omitempty"`
	Message *string      `json:"message,omitempty"`
}

func (response BlockUser201JSONResponse) VisitBlockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type BlockUser400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response BlockUser400JSONResponse) VisitBlockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type BlockUser401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response BlockUser401JSONResponse) VisitBlockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UnblockUserRequestObject struct {
	UserId string `json:"userId"`
}

type UnblockUserResponseObject interface {
	VisitUnblockUserResponse(w http.ResponseWriter) error
}

type UnblockUser200JSONResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

func (response UnblockUser200JSONResponse) VisitUnblockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UnblockUser401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UnblockUser401JSONResponse) VisitUnblockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UnblockUser404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UnblockUser404JSONResponse) VisitUnblockUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetBlockedUsersRequestObject struct {
	Params GetBlockedUsersParams
}

type GetBlockedUsersResponseObject interface {
	VisitGetBlockedUsersResponse(w http.ResponseWriter) error
}

type GetBlockedUsers200JSONResponse struct {
	Data       []BlockedUser `json:"data"`
	Pagination struct {
		Limit      int32 `json:"limit"`
		Page       int32 `json:"page"`
		Total      int32 `json:"total"`
		TotalPages int32 `json:"totalPages"`
	} `json:"pagination"`
}

func (response GetBlockedUsers200JSONResponse) VisitGetBlockedUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetBlockedUsers401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetBlockedUsers401JSONResponse) VisitGetBlockedUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LoginUserRequestObject struct {
	Body *LoginUserJSONRequestBody
}

type LoginUserResponseObject interface {
	VisitLoginUserResponse(w http.ResponseWriter) error
}

type LoginUser200JSONResponse struct {
	// Data ログインレスポンス
	Data    *LoginResponse `json:"data,omitempty"`
	Message *string        `json:"message,omitempty"`
}

func (response LoginUser200JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LoginUser401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response LoginUser401JSONResponse) VisitLoginUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LogoutUserRequestObject struct {
}

type LogoutUserResponseObject interface {
	VisitLogoutUserResponse(w http.ResponseWriter) error
}

type LogoutUser200JSONResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

func (response LogoutUser200JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type LogoutUser401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response LogoutUser401JSONResponse) VisitLogoutUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse struct {
	// Data ユーザープロフィール情報
	Data    *User   `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserProfileRequestObject struct {
	Body *UpdateUserProfileJSONRequestBody
}

type UpdateUserProfileResponseObject interface {
	VisitUpdateUserProfileResponse(w http.ResponseWriter) error
}

type UpdateUserProfile200JSONResponse struct {
	// Data ユーザープロフィール情報
	Data    *User   `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response UpdateUserProfile200JSONResponse) VisitUpdateUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserProfile400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateUserProfile400JSONResponse) VisitUpdateUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateUserProfile401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response UpdateUserProfile401JSONResponse) VisitUpdateUserProfileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetNgWordsRequestObject struct {
	Params GetNgWordsParams
}

type GetNgWordsResponseObject interface {
	VisitGetNgWordsResponse(w http.ResponseWriter) error
}

type GetNgWords200JSONResponse struct {
	Data       []NgWord `json:"data"`
	Pagination struct {
		Limit      int32 `json:"limit"`
		Page       int32 `json:"page"`
		Total      int32 `json:"total"`
		TotalPages int32 `json:"totalPages"`
	} `json:"pagination"`
}

func (response GetNgWords200JSONResponse) VisitGetNgWordsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetNgWords401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetNgWords401JSONResponse) VisitGetNgWordsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddNgWordRequestObject struct {
	Body *AddNgWordJSONRequestBody
}

type AddNgWordResponseObject interface {
	VisitAddNgWordResponse(w http.ResponseWriter) error
}

type AddNgWord201JSONResponse struct {
	// Data NGワード
	Data    *NgWord `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

func (response AddNgWord201JSONResponse) VisitAddNgWordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddNgWord400JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response AddNgWord400JSONResponse) VisitAddNgWordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddNgWord401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response AddNgWord401JSONResponse) VisitAddNgWordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNgWordRequestObject struct {
	NgWordId string `json:"ngWordId"`
}

type DeleteNgWordResponseObject interface {
	VisitDeleteNgWordResponse(w http.ResponseWriter) error
}

type DeleteNgWord200JSONResponse struct {
	Data    *map[string]interface{} `json:"data,omitempty"`
	Message *string                 `json:"message,omitempty"`
}

func (response DeleteNgWord200JSONResponse) VisitDeleteNgWordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNgWord401JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteNgWord401JSONResponse) VisitDeleteNgWordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteNgWord404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response DeleteNgWord404JSONResponse) VisitDeleteNgWordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetPublicUserInfoRequestObject struct {
	UserId string `json:"userId"`
}

type GetPublicUserInfoResponseObject interface {
	VisitGetPublicUserInfoResponse(w http.ResponseWriter) error
}

type GetPublicUserInfo200JSONResponse struct {
	// Data 公開用ユーザー情報
	Data    *PublicUserInfo `json:"data,omitempty"`
	Message *string         `json:"message,omitempty"`
}

func (response GetPublicUserInfo200JSONResponse) VisitGetPublicUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetPublicUserInfo404JSONResponse struct {
	// Data エラー詳細情報
	Data    *ErrorDetails `json:"data,omitempty"`
	Message *string       `json:"message,omitempty"`
}

func (response GetPublicUserInfo404JSONResponse) VisitGetPublicUserInfoResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// 画像ファイルをアップロード
	// (POST /api/files/images)
	UploadImage(ctx context.Context, request UploadImageRequestObject) (UploadImageResponseObject, error)
	// 画像ファイルを削除
	// (DELETE /api/files/images/{imageId})
	DeleteImage(ctx context.Context, request DeleteImageRequestObject) (DeleteImageResponseObject, error)
	// 画像ファイルを取得
	// (GET /api/files/images/{imageId})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
	// 新しい質問を送信
	// (POST /api/questions)
	CreateQuestion(ctx context.Context, request CreateQuestionRequestObject) (CreateQuestionResponseObject, error)
	// ユーザーの公開質問・回答一覧取得
	// (GET /api/questions/public/{userId})
	GetPublicQAs(ctx context.Context, request GetPublicQAsRequestObject) (GetPublicQAsResponseObject, error)
	// 受信した質問一覧取得
	// (GET /api/questions/received)
	GetReceivedQuestions(ctx context.Context, request GetReceivedQuestionsRequestObject) (GetReceivedQuestionsResponseObject, error)
	// 不適切なコンテンツを通報
	// (POST /api/questions/report)
	ReportContent(ctx context.Context, request ReportContentRequestObject) (ReportContentResponseObject, error)
	// 送信した質問一覧取得
	// (GET /api/questions/sent)
	GetSentQuestions(ctx context.Context, request GetSentQuestionsRequestObject) (GetSentQuestionsResponseObject, error)
	// 質問を削除
	// (DELETE /api/questions/{questionId})
	DeleteQuestion(ctx context.Context, request DeleteQuestionRequestObject) (DeleteQuestionResponseObject, error)
	// 質問詳細情報取得
	// (GET /api/questions/{questionId})
	GetQuestionDetail(ctx context.Context, request GetQuestionDetailRequestObject) (GetQuestionDetailResponseObject, error)
	// 質問内容を編集
	// (PATCH /api/questions/{questionId})
	UpdateQuestion(ctx context.Context, request UpdateQuestionRequestObject) (UpdateQuestionResponseObject, error)
	// 質問に回答を作成
	// (POST /api/questions/{questionId}/answer)
	CreateAnswer(ctx context.Context, request CreateAnswerRequestObject) (CreateAnswerResponseObject, error)
	// 質問を既読にマーク
	// (PATCH /api/questions/{questionId}/read)
	MarkQuestionAsRead(ctx context.Context, request MarkQuestionAsReadRequestObject) (MarkQuestionAsReadResponseObject, error)
	// 新規ユーザー登録
	// (POST /api/users)
	RegisterUser(ctx context.Context, request RegisterUserRequestObject) (RegisterUserResponseObject, error)
	// ユーザーをブロック
	// (POST /api/users/block)
	BlockUser(ctx context.Context, request BlockUserRequestObject) (BlockUserResponseObject, error)
	// ユーザーのブロックを解除
	// (DELETE /api/users/block/{userId})
	UnblockUser(ctx context.Context, request UnblockUserRequestObject) (UnblockUserResponseObject, error)
	// ブロックしたユーザー一覧取得
	// (GET /api/users/blocked)
	GetBlockedUsers(ctx context.Context, request GetBlockedUsersRequestObject) (GetBlockedUsersResponseObject, error)
	// ユーザーログイン
	// (POST /api/users/login)
	LoginUser(ctx context.Context, request LoginUserRequestObject) (LoginUserResponseObject, error)
	// ユーザーログアウト
	// (POST /api/users/logout)
	LogoutUser(ctx context.Context, request LogoutUserRequestObject) (LogoutUserResponseObject, error)
	// ログイン中のユーザー情報取得
	// (GET /api/users/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// ユーザープロフィール更新
	// (PATCH /api/users/me)
	UpdateUserProfile(ctx context.Context, request UpdateUserProfileRequestObject) (UpdateUserProfileResponseObject, error)
	// NGワード一覧取得
	// (GET /api/users/ng-words)
	GetNgWords(ctx context.Context, request GetNgWordsRequestObject) (GetNgWordsResponseObject, error)
	// NGワードを追加
	// (POST /api/users/ng-words)
	AddNgWord(ctx context.Context, request AddNgWordRequestObject) (AddNgWordResponseObject, error)
	// NGワードを削除
	// (DELETE /api/users/ng-words/{ngWordId})
	DeleteNgWord(ctx context.Context, request DeleteNgWordRequestObject) (DeleteNgWordResponseObject, error)
	// 公開ユーザー情報取得
	// (GET /api/users/{userId})
	GetPublicUserInfo(ctx context.Context, request GetPublicUserInfoRequestObject) (GetPublicUserInfoResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// UploadImage operation middleware
func (sh *strictHandler) UploadImage(ctx echo.Context) error {
	var request UploadImageRequestObject

	request.Body = ctx.Request().Body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UploadImage(ctx.Request().Context(), request.(UploadImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UploadImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UploadImageResponseObject); ok {
		return validResponse.VisitUploadImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteImage operation middleware
func (sh *strictHandler) DeleteImage(ctx echo.Context, imageId string) error {
	var request DeleteImageRequestObject

	request.ImageId = imageId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteImage(ctx.Request().Context(), request.(DeleteImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteImageResponseObject); ok {
		return validResponse.VisitDeleteImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(ctx echo.Context, imageId string) error {
	var request GetImageRequestObject

	request.ImageId = imageId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx.Request().Context(), request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		return validResponse.VisitGetImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateQuestion operation middleware
func (sh *strictHandler) CreateQuestion(ctx echo.Context) error {
	var request CreateQuestionRequestObject

	var body CreateQuestionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateQuestion(ctx.Request().Context(), request.(CreateQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateQuestionResponseObject); ok {
		return validResponse.VisitCreateQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPublicQAs operation middleware
func (sh *strictHandler) GetPublicQAs(ctx echo.Context, userId string, params GetPublicQAsParams) error {
	var request GetPublicQAsRequestObject

	request.UserId = userId
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicQAs(ctx.Request().Context(), request.(GetPublicQAsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicQAs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPublicQAsResponseObject); ok {
		return validResponse.VisitGetPublicQAsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetReceivedQuestions operation middleware
func (sh *strictHandler) GetReceivedQuestions(ctx echo.Context, params GetReceivedQuestionsParams) error {
	var request GetReceivedQuestionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReceivedQuestions(ctx.Request().Context(), request.(GetReceivedQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReceivedQuestions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetReceivedQuestionsResponseObject); ok {
		return validResponse.VisitGetReceivedQuestionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ReportContent operation middleware
func (sh *strictHandler) ReportContent(ctx echo.Context) error {
	var request ReportContentRequestObject

	var body ReportContentJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReportContent(ctx.Request().Context(), request.(ReportContentRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReportContent")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReportContentResponseObject); ok {
		return validResponse.VisitReportContentResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSentQuestions operation middleware
func (sh *strictHandler) GetSentQuestions(ctx echo.Context, params GetSentQuestionsParams) error {
	var request GetSentQuestionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSentQuestions(ctx.Request().Context(), request.(GetSentQuestionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSentQuestions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSentQuestionsResponseObject); ok {
		return validResponse.VisitGetSentQuestionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteQuestion operation middleware
func (sh *strictHandler) DeleteQuestion(ctx echo.Context, questionId string) error {
	var request DeleteQuestionRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteQuestion(ctx.Request().Context(), request.(DeleteQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteQuestionResponseObject); ok {
		return validResponse.VisitDeleteQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetQuestionDetail operation middleware
func (sh *strictHandler) GetQuestionDetail(ctx echo.Context, questionId string) error {
	var request GetQuestionDetailRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetQuestionDetail(ctx.Request().Context(), request.(GetQuestionDetailRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetQuestionDetail")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetQuestionDetailResponseObject); ok {
		return validResponse.VisitGetQuestionDetailResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateQuestion operation middleware
func (sh *strictHandler) UpdateQuestion(ctx echo.Context, questionId string) error {
	var request UpdateQuestionRequestObject

	request.QuestionId = questionId

	var body UpdateQuestionJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateQuestion(ctx.Request().Context(), request.(UpdateQuestionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateQuestion")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateQuestionResponseObject); ok {
		return validResponse.VisitUpdateQuestionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateAnswer operation middleware
func (sh *strictHandler) CreateAnswer(ctx echo.Context, questionId string) error {
	var request CreateAnswerRequestObject

	request.QuestionId = questionId

	var body CreateAnswerJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateAnswer(ctx.Request().Context(), request.(CreateAnswerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateAnswer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateAnswerResponseObject); ok {
		return validResponse.VisitCreateAnswerResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// MarkQuestionAsRead operation middleware
func (sh *strictHandler) MarkQuestionAsRead(ctx echo.Context, questionId string) error {
	var request MarkQuestionAsReadRequestObject

	request.QuestionId = questionId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.MarkQuestionAsRead(ctx.Request().Context(), request.(MarkQuestionAsReadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MarkQuestionAsRead")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(MarkQuestionAsReadResponseObject); ok {
		return validResponse.VisitMarkQuestionAsReadResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RegisterUser operation middleware
func (sh *strictHandler) RegisterUser(ctx echo.Context) error {
	var request RegisterUserRequestObject

	var body RegisterUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RegisterUser(ctx.Request().Context(), request.(RegisterUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RegisterUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RegisterUserResponseObject); ok {
		return validResponse.VisitRegisterUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// BlockUser operation middleware
func (sh *strictHandler) BlockUser(ctx echo.Context) error {
	var request BlockUserRequestObject

	var body BlockUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.BlockUser(ctx.Request().Context(), request.(BlockUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "BlockUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(BlockUserResponseObject); ok {
		return validResponse.VisitBlockUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UnblockUser operation middleware
func (sh *strictHandler) UnblockUser(ctx echo.Context, userId string) error {
	var request UnblockUserRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UnblockUser(ctx.Request().Context(), request.(UnblockUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UnblockUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UnblockUserResponseObject); ok {
		return validResponse.VisitUnblockUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetBlockedUsers operation middleware
func (sh *strictHandler) GetBlockedUsers(ctx echo.Context, params GetBlockedUsersParams) error {
	var request GetBlockedUsersRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetBlockedUsers(ctx.Request().Context(), request.(GetBlockedUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBlockedUsers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetBlockedUsersResponseObject); ok {
		return validResponse.VisitGetBlockedUsersResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LoginUser operation middleware
func (sh *strictHandler) LoginUser(ctx echo.Context) error {
	var request LoginUserRequestObject

	var body LoginUserJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LoginUser(ctx.Request().Context(), request.(LoginUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LoginUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LoginUserResponseObject); ok {
		return validResponse.VisitLoginUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// LogoutUser operation middleware
func (sh *strictHandler) LogoutUser(ctx echo.Context) error {
	var request LogoutUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LogoutUser(ctx.Request().Context(), request.(LogoutUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LogoutUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LogoutUserResponseObject); ok {
		return validResponse.VisitLogoutUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(ctx echo.Context) error {
	var request GetCurrentUserRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx.Request().Context(), request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		return validResponse.VisitGetCurrentUserResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateUserProfile operation middleware
func (sh *strictHandler) UpdateUserProfile(ctx echo.Context) error {
	var request UpdateUserProfileRequestObject

	var body UpdateUserProfileJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateUserProfile(ctx.Request().Context(), request.(UpdateUserProfileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateUserProfile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateUserProfileResponseObject); ok {
		return validResponse.VisitUpdateUserProfileResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetNgWords operation middleware
func (sh *strictHandler) GetNgWords(ctx echo.Context, params GetNgWordsParams) error {
	var request GetNgWordsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetNgWords(ctx.Request().Context(), request.(GetNgWordsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetNgWords")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetNgWordsResponseObject); ok {
		return validResponse.VisitGetNgWordsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// AddNgWord operation middleware
func (sh *strictHandler) AddNgWord(ctx echo.Context) error {
	var request AddNgWordRequestObject

	var body AddNgWordJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddNgWord(ctx.Request().Context(), request.(AddNgWordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddNgWord")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(AddNgWordResponseObject); ok {
		return validResponse.VisitAddNgWordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteNgWord operation middleware
func (sh *strictHandler) DeleteNgWord(ctx echo.Context, ngWordId string) error {
	var request DeleteNgWordRequestObject

	request.NgWordId = ngWordId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteNgWord(ctx.Request().Context(), request.(DeleteNgWordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteNgWord")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteNgWordResponseObject); ok {
		return validResponse.VisitDeleteNgWordResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetPublicUserInfo operation middleware
func (sh *strictHandler) GetPublicUserInfo(ctx echo.Context, userId string) error {
	var request GetPublicUserInfoRequestObject

	request.UserId = userId

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetPublicUserInfo(ctx.Request().Context(), request.(GetPublicUserInfoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPublicUserInfo")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetPublicUserInfoResponseObject); ok {
		return validResponse.VisitGetPublicUserInfoResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
